server.servlet.context-path: /test-demo/v1
logging.level.org.springframework.web: TRACE
spring.jackson.property-naming-strategy: SNAKE_CASE
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
management:
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    url: "jdbc:postgresql://localhost:15432/test"
    username: test
    password: "test-123456"
grpc:
  major:
    host: "localhost"
    port: 4770
  mentor:
    host: "localhost"
    port: 4770